name: Sleep Reminder Bot

on:
  schedule:
    - cron: '40 10 * * *'  # Phase 1 - ~10:40 PM NZST
    - cron: '40 11 * * *'  # Phase 2 - ~11:40 PM NZST
    - cron: '40 12 * * *'  # Phase 3 - ~12:40 AM NZST
    - cron: '10 4 * * *'   # Phase 4 - test
  workflow_dispatch:       # Manual trigger
  
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Determine script phase
        run: |
          if [[ "${{ github.event.schedule }}" == "40 10 * * *" ]]; then
            PHASE=1
          elif [[ "${{ github.event.schedule }}" == "40 11 * * *" ]]; then
            PHASE=2
          elif [[ "${{ github.event.schedule }}" == "40 12 * * *" ]]; then
            PHASE=3
          else 
            echo "⚠️ Unknown or manual trigger – defaulting to PHASE=4" 
            PHASE=1
          fi
          echo "Running phase $PHASE"
          python cron_script.py $PHASE
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
